### PR TITLE
Renovate on peerDependencies and engines.

### PR DESCRIPTION
**Pull request by KevinGrandon**

### CODE REVIEW

**Review by lhorie — APPROVED** [review]

**Comment by rarkins** [comment]
@KevinGrandon I think Renovate should already be working on peerDependencies and engines though. Also, this added packageRule won't do any thing as it is, i.e. it will successfully "select" those depTypes but then there's no other config to apply to them.

**Comment by rarkins** [comment]
While I'm looking at the config:

- buildkite is now enabled by default, so you could remove that section
- "Concurrency is limited to 1 until automerging is fully working" <- anything I should know about?

**Comment by KevinGrandon** [comment]
@rarkins - Thanks for chiming in here! 

> I think Renovate should already be working on peerDependencies and engines though.

Interesting, we are a bit behind bumping renovate PRs, but I think that for some reason we weren't seeing peerDeps bumped. E.g., if we have `^1.0.0` as a peerDep and a `1.1.0` version of that package is released, we'd like to upgrade the peerDep as well. Most likely to `^1.1.0`. Not sure if there's a renovate option for this?

> "Concurrency is limited to 1 until automerging is fully working" <- anything I should know about?

We wanted to avoid continuously rebasing multiple pull requests if they aren't automerged. I believe automerge wasn't working, due to apps not being accepted as approved reviewers? Maybe there's a fix for this though?

**Comment by rarkins** [comment]
> E.g., if we have ^1.0.0 as a peerDep and a 1.1.0 version of that package is released, we'd like to upgrade the peerDep as well. Most likely to ^1.1.0. Not sure if there's a renovate option for this?

A while back I combined this type of thing - along with pinning - into a single concept called `rangeStrategy`. By default it's `replace`, which means that if there's a new version that does not match the current range then it will replace it with the newer range, e.g. from `^1.0.0` to `^2.0.0` once v2.0.0 is released.

But if you use `config:base` then we set the default to `auto`, which means it's automagically determined by the package manager using fields like depType. So in that case `peerDependencies` would autoconfigure to `widen`. Widen would mean you go from `^1.0.0` to `^1.0.0 || ^2.0.0`. I think in the majority of cases this is best for everyone.

What you're seeking does exist, we call that rangeStrategy="bump". Basically.. You still pretend to use ranges but it keeps bumping the minimum even if the new version satisfies. So using your example of `^1.0.0` existing and v1.1.0 released, then it would be changed to `^1.1.0`. But are you totally sure you want that? You will basically end up having a very narrow range of `peerDependencies` usually just the very latest version.

> We wanted to avoid continuously rebasing multiple pull requests if they aren't automerged.

Amusingly, the buildkite team suggested we should autodetect buildkite users and *remove* all rate limiting for buildkite users (but I decided against it).

> I believe automerge wasn't working, due to apps not being accepted as approved reviewers? Maybe there's a fix for this though?

Last I checked, it's like this:

1. If you configure allowed committers to `master`, no bot can ever be added to that list - only users or groups - and so it's impossible for a feature like automerge
2. If you configure required reviewers then Renovate has to fit in and wait for someone to approve. And that means no branch automerge of course. But there is a solution! My companion app [Renovate Approve](https://github.com/apps/renovate-approve) will eagerly approve any Renovate PRs configured for automerge the instant it sees them, therefore allowing human-less automerging of PRs even if you configure mandatory reviews. Just make sure you don't configure the extra option of requiring *2* reviews minimum, or I'll have to launch a second bot..

**Comment by KevinGrandon** [comment]
> Amusingly, the buildkite team suggested we should autodetect buildkite users and _remove_ all rate limiting for buildkite users (but I decided against it).

I could see why removing rate limiting would be nice, but for us it was mainly around running lots of tests for PRs that would stack up without merging them. I think that the Renovate Approve app might solve this for us, since we do require an approved reviewer.

**Comment by KevinGrandon** [comment]
I think we're going to try peerDeps as bump, and engines as widen. We want to be aggressive in getting our library consumers to upgrade. If it doesn't work out, we'll revert. Thanks for weighing in here!

**Pull request merged**
